### PR TITLE
#13 Load documents from a text file

### LINKED ISSUE #13: Week 2: Load documents from a text file
Load data from a text file into documents to be indexed

### PR DESCRIPTION
**Pull request by rrimpila**
Added a file, read it to contents and then split it into articles with some regexing. This saves the titles into document_titles if we want to display those with the results.

And, for an example, did this all in a separate branch and created this pull request. This branch is currently up to date, so git should be able to merge the pull request automatically after approving. Also, beware, if you merge and use this code, it will try printing a horrible amount of results, since the queries match a lot of material, but #14 should fix that.

### CODE REVIEW

**Comment by tiigit** [comment]
I'm not quite sure what this pull request is, we haven't used it before on other courses. Is this something we should do when making changes to the files? Should we settle some kind of protocol on when we will use the pull request or not? Or do either of you @rrimpila @ciccmin have some other ideas on the matter? :D I'm just new to this "pull request function" in git, so now I'm not sure if I can just push my own code or if I need to make a request for you to review it before I push?

**Comment by ciccmin** [comment]
Hi! I'm also unfamiliar with pull request reviews, but iiuc these review requests must be done before merging branches, so that no change is accidentally lost when merging an outdated branch to the main branch. Since this branch is up to date, there's no issue with merging the pull request. If there are conflicts with this branch and the main one, we'd have to resolve the conflict before merging the pull.

**Comment by tiigit** [comment]
Right, okay, that sounds smart. So, does this technically work so that we accept the pull request here pushing the green "Merge pull request" button, and then what happens? Then the changes made by Raine will merge to the main branch on Git? And after that if I pull on my command line, I will get that version of the code to my local branch? Did I understand correctly :D

**Comment by ciccmin** [comment]
Yep, exactly as you said!
For more info on it there's the explanation of it in more detail:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

**Comment by tiigit** [comment]
Awesome, thanks @ciccmin !

**Comment by rrimpila** [comment]
I don't think it's necessary for us to use pull requests as a part of our workflow (unless you really want to). I figured I'd do one so you can see how they work. For strict code reviewing practices they are very useful.

**Comment by tiigit** [comment]
That was a good idea, thanks for showing us! It's good to learn these things :)

We can do pull requests maybe if someone is doing like major changes in a file, which will have impact on the things the other ones are doing? So that we'll be all on the same page when something essential in the code is changed? But maybe not when we are just adding something to the code which won't change any other aspects of the code? What do you think @rrimpila @ciccmin ?

**Pull request merged**
